server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GHBigBig/springcloudconfig.git
#          uri: git@github.com:GHBigBig/springcloudconfig.git #GitHub上面的git仓库名字 git 方式报错


